/* AUTO-GENERATED by scripts/gen_secret_scan.py — DO NOT EDIT */
#ifndef CCLAW_SECRET_SCAN_RULES_H
#define CCLAW_SECRET_SCAN_RULES_H

/* Validation types */
#define SCAN_VTYPE_PREFIX  0
#define SCAN_VTYPE_KEYWORD 1
#define SCAN_VTYPE_LITERAL 2

/* Charset classes */
#define SCAN_CHARSET_ANY         0
#define SCAN_CHARSET_UPPER_ALNUM 1
#define SCAN_CHARSET_LOWER_ALNUM 2
#define SCAN_CHARSET_ALNUM       3
#define SCAN_CHARSET_HEX         4

#define SCAN_RULE_COUNT 66

typedef struct {
    const char *id;
    const char *keyword;
    int vtype;        /* SCAN_VTYPE_PREFIX/KEYWORD/LITERAL */
    int tail_min;     /* min chars after prefix (prefix type) */
    int tail_max;     /* max chars after prefix */
    int charset;      /* SCAN_CHARSET_* */
    int nocase;       /* 1 = match anchor case-insensitively; 0 = exact case */
    float entropy;    /* min entropy threshold (0 = no check) */
} ScanRule;

static const ScanRule scan_rules[66] = {
    {"age-secret-key", "age-secret-key-1", 0, 58, 58, 3, 1, 0.0f},
    {"anthropic-admin-api-key", "sk-ant-admin01", 0, 93, 93, 3, 1, 0.0f},
    {"anthropic-api-key", "sk-ant-api03", 0, 93, 93, 3, 1, 0.0f},
    {"aws-access-token", "a3t", 0, 16, 16, 1, 1, 3.0f},
    {"aws-access-token", "akia", 0, 16, 16, 1, 1, 3.0f},
    {"aws-access-token", "asia", 0, 16, 16, 1, 1, 3.0f},
    {"aws-access-token", "abia", 0, 16, 16, 1, 1, 3.0f},
    {"aws-access-token", "acca", 0, 16, 16, 1, 1, 3.0f},
    {"databricks-api-token", "dapi", 0, 32, 32, 4, 1, 3.0f},
    {"digitalocean-access-token", "doo_v1_", 0, 64, 64, 4, 1, 3.0f},
    {"digitalocean-pat", "dop_v1_", 0, 64, 64, 4, 1, 3.0f},
    {"doppler-api-token", "dp.pt.", 0, 43, 43, 2, 1, 2.0f},
    {"flyio-access-token", "fo1_", 0, 43, 43, 3, 1, 4.0f},
    {"flyio-access-token", "fm1", 0, 43, 43, 3, 1, 4.0f},
    {"flyio-access-token", "fm2_", 0, 43, 43, 3, 1, 4.0f},
    {"gcp-api-key", "aiza", 0, 35, 35, 3, 1, 4.0f},
    {"generic-api-key", "access", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "api", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "auth", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "key", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "credential", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "creds", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "passwd", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "password", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "secret", 1, 10, 150, 3, 1, 3.5f},
    {"generic-api-key", "token", 1, 10, 150, 3, 1, 3.5f},
    {"github-app-token", "ghu_", 0, 36, 36, 3, 1, 3.0f},
    {"github-app-token", "ghs_", 0, 36, 36, 3, 1, 3.0f},
    {"github-fine-grained-pat", "github_pat_", 2, 0, 0, 0, 1, 3.0f},
    {"github-oauth", "gho_", 0, 36, 36, 3, 1, 3.0f},
    {"github-pat", "ghp_", 0, 36, 36, 3, 1, 3.0f},
    {"github-refresh-token", "ghr_", 0, 36, 36, 3, 1, 3.0f},
    {"gitlab-pat", "glpat-", 0, 20, 20, 3, 1, 3.0f},
    {"gitlab-ptt", "glptt-", 0, 40, 40, 4, 1, 3.0f},
    {"gitlab-runner-authentication-token", "glrt-", 0, 20, 20, 3, 1, 3.0f},
    {"grafana-api-key", "eyjrijoi", 0, 70, 400, 3, 1, 3.0f},
    {"grafana-cloud-api-token", "glc_", 0, 32, 400, 3, 1, 3.0f},
    {"heroku-api-key-v2", "hrku-aa", 0, 58, 58, 3, 1, 4.0f},
    {"huggingface-access-token", "hf_", 0, 34, 34, 2, 1, 2.0f},
    {"linear-api-key", "lin_api_", 0, 40, 40, 2, 1, 2.0f},
    {"notion-api-token", "ntn_", 0, 11, 11, 3, 1, 3.0f},
    {"npm-access-token", "npm_", 0, 36, 36, 2, 1, 2.0f},
    {"openai-api-key", "t3blbkfj", 0, 74, 74, 3, 1, 3.0f},
    {"perplexity-api-key", "pplx-", 0, 48, 48, 3, 1, 4.0f},
    {"private-key", "-----begin", 2, 0, 0, 0, 1, 0.0f},
    {"pypi-upload-token", "pypi-ageichlwas5vcmc", 0, 50, 1000, 3, 1, 3.0f},
    {"sendgrid-api-token", "sg.", 0, 66, 66, 3, 1, 2.0f},
    {"shopify-access-token", "shpat_", 0, 32, 32, 4, 1, 2.0f},
    {"shopify-custom-access-token", "shpca_", 0, 32, 32, 4, 1, 2.0f},
    {"slack-bot-token", "xoxb", 0, 10, 13, 3, 1, 3.0f},
    {"slack-user-token", "xoxp-", 0, 10, 13, 3, 1, 2.0f},
    {"slack-user-token", "xoxe-", 0, 10, 13, 3, 1, 2.0f},
    {"slack-webhook-url", "hooks.slack.com", 0, 43, 56, 3, 1, 0.0f},
    {"snyk-api-token", "snyk", 1, 10, 150, 3, 1, 3.5f},
    {"sourcegraph-access-token", "sgp_", 0, 16, 16, 4, 1, 3.0f},
    {"sourcegraph-access-token", "sourcegraph", 0, 16, 16, 4, 1, 3.0f},
    {"stripe-access-token", "sk_test", 0, 10, 99, 3, 1, 2.0f},
    {"stripe-access-token", "sk_live", 0, 10, 99, 3, 1, 2.0f},
    {"stripe-access-token", "sk_prod", 0, 10, 99, 3, 1, 2.0f},
    {"stripe-access-token", "rk_test", 0, 10, 99, 3, 1, 2.0f},
    {"stripe-access-token", "rk_live", 0, 10, 99, 3, 1, 2.0f},
    {"stripe-access-token", "rk_prod", 0, 10, 99, 3, 1, 2.0f},
    {"telegram-bot-api-token", "telegr", 1, 10, 150, 3, 1, 3.5f},
    {"twilio-api-key", "SK", 0, 32, 32, 4, 0, 3.0f},
    {"vault-batch-token", "hvb.", 0, 138, 300, 3, 1, 4.0f},
    {"vault-service-token", "hvs.", 0, 90, 120, 3, 1, 3.5f},
};

#endif /* CCLAW_SECRET_SCAN_RULES_H */
